version: '3.8'

services:
  file-converter:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: file-converter
    volumes:
      - "./:/usr/src/app:cached"
      - "./data:/data"
    ports:
      - "5152:5152"
    networks:
      - file-net

networks:
  file-net:
    driver: bridge
